org: rafaelram
service: web-scraping-igp

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::969784661290:role/LabRole

functions:
  scrape_igp:
    handler: web_scraping_api.lambda_handler
    package:
      include:
        - web_scraping_api.py
    events:
      - http:
          path: /scrape/json
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    SismosReportados:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: t_sismos
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
